const $=s=>document.querySelector(s), source=$('#source');let trace=[],step=0,lastResult=null,examples={};
async function api(path,payload){busy(true);try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!j.ok)throw Error(j.error);ok();return j.data}catch(e){fail(e.message);throw e}finally{busy(false)}}
function busy(v){document.body.classList.toggle('busy',v)}function ok(){document.body.classList.remove('error');$('#diagnostic').textContent='NO DIAGNOSTICS'}function fail(){document.body.classList.add('error');$('#diagnostic').textContent='DIAGNOSTIC'}
function updateLines(){const n=source.value.split('\n').length;$('#lines').textContent=Array.from({length:n},(_,i)=>i+1).join('\n');localStorage.setItem('clio-source',source.value)}source.addEventListener('input',updateLines);source.addEventListener('scroll',()=>{$('#lines').scrollTop=source.scrollTop});
async function run(){const data=await api('/api/run',{source:source.value});lastResult=data;renderResult(data);const inspected=await api('/api/inspect',{source:source.value});renderTrace(inspected.trace.events);const observed=await api('/api/observe',{source:source.value});$('#norm').textContent=`NORM ${observed.norm_squared.toFixed(12)}`}
function renderResult(r){$('#p-status').textContent=r.final_state.status;$('#pc').textContent=r.final_state.program_counter;$('#seed').textContent=`${r.seed} / ${r.final_state.shot_index+1} OF ${r.shots}`;chips('#qubits',r.final_state.virtual_qubits.map(q=>[`q${q}`,'ALLOC']));chips('#registers',r.final_state.classical_registers.map((v,i)=>[`r${i}`,v]).filter(x=>x[1]!==0));chips('#measurements',r.final_state.measurement_registers.map((v,i)=>[`m${i}`,v]).filter(x=>x[1]!=='Unset'));$('#resources').innerHTML=`${r.plan.qubits} qubits<br>${fmt(r.plan.estimated_total_bytes)} admitted<br>${r.plan.estimated_instructions} instructions`;const total=Object.values(r.measurement_counts).reduce((a,b)=>a+b,0);$('#counts').classList.remove('muted');$('#counts').innerHTML=Object.entries(r.measurement_counts).sort().map(([k,v])=>`<div class="row"><b>${k}</b><i class="fill" style="width:${100*v/total}%"></i><span>${v}</span></div>`).join('')}
function chips(sel,data){const e=$(sel);e.classList.toggle('muted',!data.length);e.innerHTML=data.length?data.map(([k,v])=>`<span class="chip">${k} <b>${v}</b></span>`).join(''):'None'}
function renderTrace(events){trace=events;step=Math.max(0,events.length-1);$('#scrubber').max=Math.max(0,events.length-1);$('#scrubber').value=step;$('#timeline').classList.remove('empty');$('#timeline').innerHTML=events.map((e,i)=>`<div class="event" data-i="${i}"><span>${String(e.step).padStart(4,'0')}</span><strong>${e.mnemonic}</strong><span>${e.measurement?`<em>m${e.measurement.register} = ${e.measurement.value?1:0}</em>`:e.branch_taken!==null?`branch ${e.branch_taken?'taken':'skipped'}`:e.status_after}</span></div>`).join('');showStep(step)}
function showStep(i){if(!trace.length)return;step=Math.max(0,Math.min(i,trace.length-1));$('#scrubber').value=step;$('#step-label').textContent=`STEP ${trace[step].step}`;document.querySelectorAll('.event').forEach((e,j)=>e.classList.toggle('active',j===step));document.querySelector(`.event[data-i="${step}"]`)?.scrollIntoView({block:'nearest'});const snap=trace[step].state_snapshot;if(snap){$('#statevector').classList.remove('empty');$('#statevector').innerHTML=snap.map(a=>`<div class="basis"><b>|${a.basis_index.toString(2).padStart(Math.log2(snap.length),'0')}〉</b><span class="bar"><i style="width:${Math.min(100,a.probability*100)}%"></i></span><small>${a.real.toFixed(4)} ${a.imaginary<0?'−':'+'} ${Math.abs(a.imaginary).toFixed(4)}i</small></div>`).join('')}}
$('#run').onclick=()=>run().catch(()=>{});$('#build').onclick=()=>api('/api/build',{source:source.value}).catch(()=>{});$('#validate').onclick=()=>api('/api/validate',{source:source.value}).then(d=>{$('#validation').textContent=JSON.stringify(d,null,2);document.querySelector('[data-tab="results"]').click()}).catch(()=>{});$('#prev').onclick=()=>showStep(step-1);$('#next').onclick=()=>showStep(step+1);$('#scrubber').oninput=e=>showStep(+e.target.value);document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tabview').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')});
fetch('/api/examples').then(r=>r.json()).then(j=>{examples=j.data||j;Object.keys(examples).forEach(k=>$('#examples').add(new Option(k.toUpperCase(),k)));const saved=localStorage.getItem('clio-source');source.value=saved||examples.bell;updateLines()});$('#examples').onchange=e=>{if(examples[e.target.value]){source.value=examples[e.target.value];updateLines()}};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run().catch(()=>{})}});function fmt(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KiB`:`${(n/1048576).toFixed(1)} MiB`}
